<?php include ("netlib.php"); ?><!DOCTYPE.phpL PUBLIC "-//W3C//DTD.phpL 4.01 Transitional//EN"><head><title>We ship anything anywhere. Get it there!</title><meta http-equiv="Content-Type" content="text.phpl; charset=iso-8859-1"><script language="JavaScript" type="text/JavaScript"><!--function MM_reloadPage(init) {  //reloads the window if Nav4 resized  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();}MM_reloadPage(true);//--></script></head><body><table width="994" border="0" cellpadding="0" cellspacing="0">  <!--DWLayoutTable-->  <tr>     <td height="87" colspan="3" valign="top"><img src="pictures/logo.jpg" width="321" height="87"></td>    <td colspan="5" valign="top"><img src="pictures/l2.jpg" width="672" height="87"></td>    <td width="1"></td>  </tr>  <tr>     <td height="27" colspan="3" valign="top"><a href="company.php"><img src="pictures/butoane/company.jpg" alt="Shipping_company" width="89" height="27" border="0"></a><a href="why_us.php"><img src="pictures/butoane/whyus.jpg" alt="Shipping_company" width="85" height="27" border="0"></a><a href="faq.php"><img src="pictures/butoane/faq.jpg" alt="Shipping_company" width="68" height="27" border="0"></a><a href="contact.php"><img src="pictures/butoane/contact.jpg" alt="contact_us" width="79" height="27" border="0"></a></td>    <td width="347" rowspan="4" valign="top"><img src="pictures/l3.jpg" width="347" height="94"></td>    <td colspan="4" valign="top"><a href="thrd_how_it_works.php"><img src="pictures/butoane/howworks.jpg" alt="third_party_agency" width="116" height="27" border="0"></a><a href="thrd_why_use_it.php"><img src="pictures/butoane/whyuseit.jpg" alt="third_party_agency" width="87" height="27" border="0"></a><a href="thrd_fees.php"><img src="pictures/butoane/fees.jpg" alt="third_party_agency" width="51" height="27" border="0"></a><a href="thrd_agency.php"><img src="pictures/butoane/agency.jpg" alt="third_party_agency" width="66" height="27" border="0"></a></td>    <td></td>  </tr>  <tr>     <td colspan="3" rowspan="3" valign="top"><img src="pictures/tracking.jpg" width="248" height="50"></td>    <td width="169" height="19">&nbsp;</td>    <td width="45">&nbsp;</td>    <td width="101"></td>    <td width="10"></td>    <td></td>  </tr>  <tr>     <td height="19">&nbsp;</td>    <td colspan="2" valign="top"><a href="company.php"><img src="pictures/butoane/home.jpg" width="69" height="19" border="0"></a><img src="pictures/butoane/track.jpg" width="77" height="19"></td>    <td>&nbsp;</td>    <td></td>  </tr>  <tr>     <td height="29">&nbsp;</td>    <td>&nbsp;</td>    <td></td>    <td></td>    <td></td>  </tr>      <tr>
<td height="32" colspan="2" valign="top"><!--DWLayoutEmptyCell-->&nbsp;</td>    
        <td colspan="6" rowspan="2" valign="top" background="pictures/tracking3.jpg">
            <p align="justify">&nbsp;       </p>
            <p align="justify"><font color="#000000" size="2" face="Arial, Helvetica, sans-serif">Tracking         Number Result: <strong><font color="#666666">Package not Found</font></strong></font></p>
            <p><font color="#000000" size="2" face="Arial, Helvetica, sans-serif">No         scan record for the following shipment has been received by our system         yet. Please try again later tracking your shipment or </font><font size="2" face="Arial, Helvetica, sans-serif">check         again your <font color="#333333"><strong>Tracking Number</strong></font></font><font color="#000000" size="2" face="Arial, Helvetica, sans-serif">.</font></p>
            <p><font size="2" face="Arial,Helvetica" color="black">International Cargo Spedition </font><font color="#000000" size="2" face="Arial, Helvetica, sans-serif">authorises you to use tracking systems solely to track shipments. Any         other use of tracking systems and information is strictly prohibited.</font><br>        <br>      </p>
        </td>
<td></td>  
    </tr>
<tr>     <td colspan="2" rowspan="2" valign="top"> <p><a href="instant_quote_mrch.php"><img src="pictures/butoane/sndpackage.jpg" width="140" height="109" border="0"></a></p>      <p>&nbsp;</p></td>    <td height="146"></td>  </tr>  <tr>     <td width="175" height="1"></td>    <td></td>    <td></td>    <td></td>    <td></td>    <td></td>    <td></td>  </tr>  <tr>     <td width="137" rowspan="5" valign="top"><img src="pictures/blueman3.jpg" width="137" height="295"></td>    <td width="9" rowspan="3" valign="top"><!--DWLayoutEmptyCell-->&nbsp;</td>    <td height="33" colspan="6" valign="top"><!--DWLayoutEmptyCell-->&nbsp;</td>    <td></td>  </tr>      <tr>
        <td colspan="4" rowspan="2" valign="top">
            <p><font size="2" face="Arial, Helvetica, sans-serif"><br>        <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="100" height="23">
            <param name="BGCOLOR" value="">
            <param name="BASE" value=".">
            <param name="movie" value="button2.swf">
            <param name="quality" value="high">
<embed src="button2.swf" width="100" height="23" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" BASE="." BGCOLOR></embed>         </object>        </font></p>
            <p><font size="2" face="Arial, Helvetica, sans-serif">If you can not track         your package online, please check again your <font color="#333333"><strong>Tracking         Number, </strong></font>call</font><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><strong><font size="2" face="Arial, Helvetica, sans-serif"><strong><font size="2" face="Arial, Helvetica, sans-serif"> </font></strong></font></strong></font><font size="2" face="Arial,Helvetica" color="#666666"><strong>International Cargo Spedition</strong></font><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><strong><font size="2" face="Arial, Helvetica, sans-serif"><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><strong><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><strong><font size="2" face="Arial, Helvetica, sans-serif"><font color="#666666" size="2" face="Arial, Helvetica, sans-serif"><strong><font size="2" face="Arial, Helvetica, sans-serif"><strong><strong> Company</strong></strong></font></strong></font></font></strong></font></strong></font></font></strong></font><font size="2" face="Arial, Helvetica, sans-serif"> at </font><font size="1" face="Arial, Helvetica, sans-serif">         <font size="2"> +44 7979-4141-07, or email us</font></font><font size="2" face="Arial, Helvetica, sans-serif">         to send your tracking number again. </font></p>
        </td>
<td height="18"></td>    <td></td>    <td></td>  
    </tr>
<tr>     <td colspan="2" rowspan="4" valign="top"><img src="pictures/halfcircle.jpg" width="111" height="258"></td>    <td height="130"></td>  </tr>  <tr>     <td height="49" colspan="5" valign="top" background="pictures/grey3.jpg"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="745" height="49">        <param name="movie" value="swf/Transaction_company.swf">        <param name="quality" value="high">        <embed src="swf/Transaction_company.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="745" height="49"></embed></object></td>    <td></td>  </tr>  <tr>     <td height="65" colspan="5" valign="top"><img src="pictures/txt3.jpg" width="745" height="65"></td>    <td></td>  </tr>  <tr>     <td height="14" colspan="6" valign="top"><img src="pictures/foots.jpg" width="137" height="14"><img src="pictures/copyright2.jpg" width="745" height="14" border="0" usemap="#Map"></td>    <td></td>  </tr></table><div align="center"></div><map name="Map">  <area shape="rect" coords="437,1,491,13" href="thrd_privacy_policy.php"></map></body>